Repository gammasim/simtools, pull requests merged in 2023-12, with the labels that each got.

#712 Improve startup time of pytest by optimising imports
  tests/conftest.py
Labels: Less than 15-min Pull Request Review

#704 Review of general.py
  simtools/corsika/corsika_histograms.py
  simtools/model/camera.py
  simtools/utils/general.py
  simtools/utils/geometry.py
  simtools/visualization/visualize.py
  tests/conftest.py
  tests/unit_tests/corsika/test_corsika_runner.py
  tests/unit_tests/simtel/test_simtel_config_writer.py
  tests/unit_tests/utils/test_general.py
  tests/unit_tests/utils/test_geometry.py
Labels: 2023_maintenance

#714 Pass corsika_parameters_file to CorsikaConfig in corsika_runner
  simtools/corsika/corsika_runner.py
Labels: Less than 15-min Pull Request Review

#684 Linter updates
  .github/workflows/CI-linter.yml
  .github/workflows/CI-unittests.yml
  .pre-commit-config.yaml
  README.rst
  docker/README.md
  docs/source/coding_guidelines.rst
  docs/source/conf.py
  pyproject.toml
  simtools/applications/add_file_to_db.py
  simtools/applications/compare_cumulative_psf.py
  simtools/applications/generate_corsika_histograms.py
  simtools/applications/generate_default_metadata.py
  simtools/applications/generate_simtel_array_histograms.py
  simtools/applications/sim_showers_for_trigger_rates.py
  simtools/applications/tune_psf.py
  simtools/applications/validate_camera_fov.py
  simtools/applications/validate_file_using_schema.py
  simtools/applications/validate_optics.py
  simtools/corsika/corsika_config.py
  simtools/corsika/corsika_histograms.py
  simtools/corsika/corsika_histograms_visualize.py
  simtools/corsika_simtel/corsika_simtel_runner.py
  simtools/data_model/metadata_collector.py
  simtools/data_model/model_data_writer.py
  simtools/db_handler.py
  simtools/io_operations/hdf5_handler.py
  simtools/model/telescope_model.py
  simtools/psf_analysis.py
  simtools/simtel/simtel_histograms.py
  simtools/simtel/simtel_runner.py
  simtools/simtel/simtel_runner_array.py
  simtools/simtel/simtel_runner_camera_efficiency.py
  simtools/simtel/simtel_runner_ray_tracing.py
  simtools/utils/geometry.py
  simtools/visualization/visualize.py
  tests/integration_tests/test_applications.py
  tests/unit_tests/corsika/test_corsika_histograms.py
  tests/unit_tests/corsika/test_corsika_histograms_visualize.py
  tests/unit_tests/corsika_simtel/test_corsika_simtel_runner.py
  tests/unit_tests/simtel/test_simtel_histograms.py
  tests/unit_tests/utils/test_geometry.py
  tests/unit_tests/visualization/test_visualize.py
Labels: 2023_maintenance

#721 Add pytest-random-order to development environment.
  docs/source/developer_guidelines.rst
  environment.yml
  pyproject.toml
Labels: 2023_maintenance

#734 Add codecov configuration file to suppress failed tests when coverage falls by 0.1%
  codecov.yml
Labels: Less than 15-min Pull Request Review

#736 Random state set to none
  simtools/corsika_simtel/corsika_simtel_runner.py
  simtools/simtel/simtel_runner_array.py
  simtools/simtel/simtel_runner_ray_tracing.py
Labels: Less than 15-min Pull Request Review

#731 remove unused functions from simulator
  simtools/simtel/simtel_histograms.py
  simtools/simulator.py
  tests/unit_tests/simtel/test_simtel_histograms.py
  tests/unit_tests/test_simulator.py
Labels: 2023_maintenance, Less than 15-min Pull Request Review

#735 Zero padding corsika output file
  simtools/corsika/corsika_config.py
  simtools/corsika/corsika_runner.py
  tests/unit_tests/corsika/test_corsika_config.py
Labels: Less than 15-min Pull Request Review

#744 Increase speed of simtel histograms test
  simtools/applications/generate_corsika_histograms.py
  simtools/applications/generate_simtel_array_histograms.py
  tests/integration_tests/config/generate_corsika_histograms_1D_run_header.yml
  tests/integration_tests/config/generate_corsika_histograms_1d_and_2d_run_header.yml
  tests/integration_tests/config/generate_corsika_histograms_2D_run_header.yml
  tests/integration_tests/config/generate_corsika_histograms_figures.yml
  tests/integration_tests/config/generate_corsika_histograms_figures_and_tables.yml
  tests/integration_tests/config/generate_corsika_histograms_individual_telescopes_and_indices.yml
  tests/integration_tests/config/generate_corsika_histograms_output.yml
  tests/integration_tests/config/generate_corsika_histograms_tables.yml
  tests/integration_tests/config/generate_corsika_histograms_telescope_indices.yml
  tests/integration_tests/config/generate_simtel_array_histograms_file_lists.yml
  tests/integration_tests/config/generate_simtel_array_histograms_hist_file_names.yml
  tests/integration_tests/config/generate_simtel_array_histograms_hist_file_names_pdf_hdf5.yml
  tests/integration_tests/config/generate_simtel_array_histograms_hist_file_names_pdf_no_name.yml
Labels: 2023_maintenance

#747 Old production tool real test
  simtools/applications/production.py
  simtools/simtel/simtel_runner_array.py
  tests/integration_tests/config/production_array_only.yml
  tests/integration_tests/config/production_showers_only.yml
  tests/integration_tests/test_applications_from_config.py
Labels: 2023_maintenance

#751 Docker images for simtools-dev and simtools-prod should not be pushed on "pull request"
  .github/workflows/build-docker-images.yml
Labels: Less than 15-min Pull Request Review
