Repository gammasim/simtools, pull requests merged in 2024-06, with the labels that each got.

#957 First version of CTAO DPPS sonarqube workflow
  .github/workflows/CI-unittests.yml
  README.md
  sonar-project.properties
Labels: testing

#995 update ruff
  .pre-commit-config.yaml
Labels: dependencies

#990 Docstring applications commands
  simtools/applications/calculate_trigger_rate.py
  simtools/applications/db_add_file_to_db.py
  simtools/applications/derive_psf_parameters.py
  simtools/applications/generate_array_config.py
  simtools/applications/generate_corsika_histograms.py
  simtools/applications/generate_simtel_array_histograms.py
Labels: documentation
