Repository gammasim/simtools, pull requests merged in 2025-09, with the labels that each got.

#1705 Consistent naming of plotting routines
  docs/source/api-reference/visualization.md
  src/simtools/applications/plot_simtel_events.py
  src/simtools/visualization/plot_simtel_events.py
  tests/unit_tests/visualization/test_plot_simtel_events.py
Labels: no-changelog-needed

#1739 Fix sonar coverage for unit tests
  .github/workflows/CI-unittests.yml
Labels: no-changelog-needed

#1743 Small bug fix in help for upload_from_model_repository_to_db.sh
  database_scripts/upload_from_model_repository_to_db.sh
Labels: no-changelog-needed

#1772 Unit tests should not write into the source tree
  docs/source/developer-guide/testing.md
  tests/unit_tests/camera/test_single_photon_electron_spectrum.py
  tests/unit_tests/io/test_ascii_handler.py
  tests/unit_tests/io/test_io_handler.py
  tests/unit_tests/production_configuration/test_derive_corsika_limits.py
  tests/unit_tests/production_configuration/test_generate_production_grid.py
  tests/unit_tests/production_configuration/test_merge_corsika_limits.py
  tests/unit_tests/ray_tracing/test_incident_angles.py
  tests/unit_tests/reporting/test_docs_read_parameters.py
  tests/unit_tests/runners/test_simtools_runner.py
  tests/unit_tests/simtel/test_simtel_config_writer.py
  tests/unit_tests/simtel/test_simtel_io_event_reader.py
  tests/unit_tests/test_simulator.py
  tests/unit_tests/testing/test_validate_output.py
  tests/unit_tests/visualization/test_plot_incident_angles.py
Labels: no-changelog-needed, Skip review

#1775 Clarify DB upload in documentation
  database_scripts/upload_from_model_repository_to_db.sh
  docs/changes/1775.doc.md
  docs/source/components/databases.md
  docs/source/user-guide/manage_simulation_models/simulation_models_database.md
Labels: Skip review
